### PR TITLE
Updater UI rewrite

### PR DESCRIPTION
**Pull request by dmex**
Completed initial updater rewrite

### CODE REVIEW

**Comment by wj32** [comment]
Have you tested this with error conditions (e.g. no network connection, hash failed, etc.)?

**Comment by dmex** [comment]
Yeah, there are defines in updater.h for testing errors but not for failed network connections... It shows a generic error page and might need some special handling.

**Comment by wj32** [comment]
What's the point of InitializedEvent? You don't seem to wait on it anywhere.

**Comment by dmex** [comment]
ShowUpdateDialog waits on the InitializedEvent since it needs a valid window handle to send the WM_SHOWDIALOG notification

**Pull request merged**
