### PR TITLE
Rename readme, hacking and copyright files to enable github formatting

### PR DESCRIPTION
**Pull request by TETYYS**

### CODE REVIEW

**Comment by wj32** [comment]
These files are distributed in the binary package and setup exe, and I don't want users to have to try to open a .md file.

**Comment by TETYYS** [comment]
oh ok

also what happened here

**Comment by wj32** [comment]
Sorry you'll have to delete and clone the repo again because we rewrote the history to fix dmex's email address.

**Comment by TETYYS** [comment]
no worries

**Pull request closed without merging**
